# Generated by Django 4.1 on 2024-07-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nonunique_network_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='networkedge',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='rastermaplayer',
            name='file_item',
        ),
        migrations.RemoveField(
            model_name='vectormaplayer',
            name='file_item',
        ),
        migrations.AddField(
            model_name='rastermaplayer',
            name='dataset',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dataset'
            ),
        ),
        migrations.AddField(
            model_name='vectormaplayer',
            name='dataset',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dataset'
            ),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('category', models.CharField(max_length=25)),
                ('metadata', models.JSONField(blank=True, null=True)),
                (
                    'dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='networks',
                        to='core.dataset',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='networkedge',
            name='network',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='edges',
                to='core.network',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networknode',
            name='network',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='nodes',
                to='core.network',
            ),
            preserve_default=False,
        ),
    ]
