# Generated by Django 5.0.7 on 2024-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='default_map_zoom',
            field=models.FloatField(default=10),
        ),
    ]
