# Generated by Django 5.0.7 on 2025-01-31 18:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields

import geoinsight.core.models.layer


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_file_size_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceregion',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='vectormaplayer',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='vectorfeature',
            name='map_layer',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_type',
        ),
        migrations.RemoveField(
            model_name='network',
            name='dataset',
        ),
        migrations.AddField(
            model_name='network',
            name='name',
            field=models.CharField(default='Network', max_length=255),
        ),
        migrations.AddField(
            model_name='networkedge',
            name='vector_feature',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='edges',
                to='core.vectorfeature',
            ),
        ),
        migrations.AddField(
            model_name='networknode',
            name='vector_feature',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='nodes',
                to='core.vectorfeature',
            ),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='Layer', max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                (
                    'dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='layers',
                        to='core.dataset',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RasterData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='Raster Data', max_length=255)),
                ('cloud_optimized_geotiff', s3_file_field.fields.S3FileField(null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                (
                    'dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rasters',
                        to='core.dataset',
                    ),
                ),
                (
                    'source_file',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fileitem'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                (
                    'dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='regions',
                        to='core.dataset',
                    ),
                ),
                (
                    'vector_feature',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='regions',
                        to='core.vectorfeature',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='VectorData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='Vector Data', max_length=255)),
                ('geojson_data', s3_file_field.fields.S3FileField(null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                (
                    'dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vectors',
                        to='core.dataset',
                    ),
                ),
                (
                    'source_file',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fileitem'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LayerFrame',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='Layer Frame', max_length=255)),
                ('index', models.PositiveIntegerField(default=0)),
                (
                    'source_filters',
                    models.JSONField(default=geoinsight.core.models.layer.default_source_filters),
                ),
                ('metadata', models.JSONField(blank=True, null=True)),
                (
                    'layer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='frames',
                        to='core.layer',
                    ),
                ),
                (
                    'raster',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rasterdata'
                    ),
                ),
                (
                    'vector',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vectordata'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='vector_data',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='networks',
                to='core.vectordata',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vectorfeature',
            name='vector_data',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='features',
                to='core.vectordata',
            ),
        ),
        migrations.DeleteModel(
            name='RasterMapLayer',
        ),
        migrations.DeleteModel(
            name='SourceRegion',
        ),
        migrations.DeleteModel(
            name='VectorMapLayer',
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(
                fields=('dataset', 'name'), name='unique-source-region-name'
            ),
        ),
        migrations.AddConstraint(
            model_name='layerframe',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('raster__isnull', False), ('vector__isnull', True)),
                    models.Q(('raster__isnull', True), ('vector__isnull', False)),
                    _connector='OR',
                ),
                name='exactly_one_data',
            ),
        ),
    ]
