# Generated by Django 5.0.7 on 2025-03-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_layers_and_frames'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('analysis_type', models.CharField(max_length=25)),
                ('inputs', models.JSONField(blank=True, null=True)),
                ('outputs', models.JSONField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(null=True)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='analysis_results',
                        to='core.project',
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='SimulationResult',
        ),
    ]
