# Generated by Django 4.1 on 2023-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_models_redesign'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vectortile',
            index=models.Index(fields=['z', 'x', 'y'], name='vectortile-coordinates-index'),
        ),
        migrations.AddConstraint(
            model_name='vectortile',
            constraint=models.UniqueConstraint(
                fields=('map_layer', 'z', 'x', 'y'), name='unique-map-layer-index'
            ),
        ),
    ]
