# Generated by Django 4.1 on 2024-06-24 18:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_models_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorFeature',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('properties', models.JSONField()),
                (
                    'map_layer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.vectormaplayer'
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='VectorTile',
        ),
    ]
