# Generated by Django 4.1 on 2024-06-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vector_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastermaplayer',
            name='file_item',
        ),
        migrations.RemoveField(
            model_name='vectormaplayer',
            name='file_item',
        ),
        migrations.AddField(
            model_name='rastermaplayer',
            name='dataset',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dataset'
            ),
        ),
        migrations.AddField(
            model_name='vectormaplayer',
            name='dataset',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dataset'
            ),
        ),
    ]
