# Generated by Django 4.1 on 2023-11-02 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_vectortile_vectortile-coordinates-index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vectormaplayer',
            old_name='large_geojson_data',
            new_name='geojson_file',
        ),
        migrations.RemoveField(
            model_name='vectormaplayer',
            name='geojson_data',
        ),
    ]
