# Generated by Django 4.1 on 2023-07-11 12:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_processing_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='network',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('adjacent_nodes', models.ManyToManyField(to='core.networknode')),
                (
                    'dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='network_nodes',
                        to='core.dataset',
                    ),
                ),
            ],
        ),
    ]
