# Generated by Django 4.1 on 2024-06-24 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_vectorfeature_attributes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VectorTile',
        ),
    ]
