# Generated by Django 4.1 on 2023-08-23 20:55

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=25)),
                ('raw_data_file', s3_file_field.fields.S3FileField(blank=True, null=True)),
                ('raw_data_type', models.CharField(default='csv', max_length=25)),
                ('chart_data', models.JSONField(blank=True, null=True)),
                ('chart_options', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('style', models.JSONField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='core.city')),
            ],
        ),
    ]
