# Generated by Django 5.0.7 on 2024-10-28 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_alter_project_default_map_zoom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DerivedRegion',
        ),
    ]
