# Generated by Django 5.0.7 on 2024-11-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_derivedregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresult',
            name='simulation_type',
            field=models.CharField(
                choices=[
                    ('FLOOD_1', 'Flood Scenario 1'),
                    ('RECOVERY', 'Recovery Scenario'),
                    ('SEGMENT_CURBS', 'Segment Curbs'),
                ],
                max_length=13,
            ),
        ),
    ]
