# Generated by Django 4.1 on 2023-09-27 19:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_simulation_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('source_operation', models.CharField(choices=[('UNION', 'Union'), ('INTERSECTION', 'Intersection')], max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('dataset', 'name'), name='unique-name-per-dataset'),
        ),
        migrations.AddField(
            model_name='derivedregion',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_regions', to='core.city'),
        ),
        migrations.AddField(
            model_name='derivedregion',
            name='source_regions',
            field=models.ManyToManyField(related_name='derived_regions', to='core.region'),
        ),
        migrations.AddConstraint(
            model_name='derivedregion',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='unique-name-per-city'),
        ),
    ]
