# Generated by Django 5.0.7 on 2025-05-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerStyle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='Layer Style', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('style_spec', models.JSONField(blank=True, default=dict)),
                (
                    'layer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='styles',
                        to='core.layer',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='styles',
                        to='core.project',
                    ),
                ),
            ],
        ),
    ]
