# Generated by Django 5.0.7 on 2025-07-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerStyle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='Layer Style', max_length=255)),
                ('style_spec', models.JSONField(blank=True, default=dict)),
                (
                    'layer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='styles',
                        to='core.layer',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='styles',
                        to='core.project',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='default_style',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='default_layer',
                to='core.layerstyle',
            ),
        ),
        migrations.AddConstraint(
            model_name='layerstyle',
            constraint=models.UniqueConstraint(
                fields=('name', 'layer', 'project'), name='unique_name_layer_project'
            ),
        ),
    ]
