# Generated by Django 5.0.7 on 2025-07-01 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_layer_styles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerstyle',
            name='is_default',
        ),
        migrations.AddField(
            model_name='layer',
            name='default_style',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='default_layer',
                to='core.layerstyle',
            ),
        ),
        migrations.AddConstraint(
            model_name='layerstyle',
            constraint=models.UniqueConstraint(
                fields=('name', 'layer', 'project'), name='unique_name_layer_project'
            ),
        ),
    ]
