# Generated by Django 5.0.7 on 2025-09-22 14:31

import json
from pathlib import Path

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    colormap_model = apps.get_model('core', 'Colormap')
    default_colormaps_file = Path(settings.BASE_DIR, 'uvdat', 'core', 'models', 'colormaps.json')
    with open(default_colormaps_file) as f:
        default_colormaps = json.load(f)
        for default_colormap in default_colormaps:
            name = default_colormap.get('name')
            markers = default_colormap.get('markers')
            if name is not None and markers is not None:
                colormap_model.objects.create(
                    name=name,
                    markers=markers,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_task_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colormap',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('markers', models.JSONField(default=list)),
                (
                    'project',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='colormaps',
                        to='core.project',
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ColormapConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('color_by', models.CharField(max_length=255)),
                ('null_color', models.CharField(max_length=7)),
                ('discrete', models.BooleanField(default=False)),
                (
                    'n_colors',
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                ('range_minimum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('range_maximum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                (
                    'colormap',
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name='colormap_configs',
                        to='core.colormap',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ColorConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('single_color', models.CharField(max_length=7, null=True)),
                (
                    'style',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='color_configs',
                        to='core.layerstyle',
                    ),
                ),
                (
                    'colormap',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='color_configs',
                        to='core.colormapconfig',
                    ),
                ),
            ],
        ),
    ]
