# Generated by Django 5.0.7 on 2025-09-22 14:31

import json
from pathlib import Path

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    colormap_model = apps.get_model('core', 'Colormap')
    default_colormaps_file = Path(settings.BASE_DIR, 'uvdat', 'core', 'models', 'colormaps.json')
    with open(default_colormaps_file) as f:
        default_colormaps = json.load(f)
        for default_colormap in default_colormaps:
            name = default_colormap.get('name')
            markers = default_colormap.get('markers')
            if name is not None and markers is not None:
                colormap_model.objects.create(
                    name=name,
                    markers=markers,
                )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_task_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colormap',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('markers', models.JSONField(default=list)),
                (
                    'project',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='colormaps',
                        to='core.project',
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards, backwards),
    ]
