# Generated by Django 5.0.7 on 2025-10-08 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import uvdat


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_colormaps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerstyle',
            name='style_spec',
        ),
        migrations.AddField(
            model_name='layerstyle',
            name='default_frame',
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name='layerstyle',
            name='opacity',
            field=models.DecimalField(
                decimal_places=1,
                default=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.CreateModel(
            name='ColorConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('single_color', models.CharField(max_length=12, null=True)),
                (
                    'style',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='color_configs',
                        to='core.layerstyle',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ColormapConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('color_by', models.CharField(max_length=255)),
                ('null_color', models.CharField(max_length=12)),
                ('clamp', models.BooleanField(default=False)),
                ('discrete', models.BooleanField(default=False)),
                (
                    'n_colors',
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                ('range_minimum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('range_maximum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                (
                    'color_config',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='colormap',
                        to='core.colorconfig',
                    ),
                ),
                (
                    'colormap',
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(uvdat.core.models.styles.get_default_colormap),
                        related_name='colormap_configs',
                        to='core.colormap',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='FilterConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('filter_by', models.CharField(max_length=255)),
                ('include', models.BooleanField(default=True)),
                ('transparency', models.BooleanField(default=True)),
                ('range_minimum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('range_maximum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('values_list', models.JSONField(null=True)),
                (
                    'style',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='filter_configs',
                        to='core.layerstyle',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SizeConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('zoom_scaling', models.BooleanField(default=True)),
                (
                    'single_size',
                    models.IntegerField(
                        default=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    'style',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='size_configs',
                        to='core.layerstyle',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SizeRangeConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('size_by', models.CharField(max_length=255)),
                (
                    'minimum',
                    models.IntegerField(
                        default=3, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    'maximum',
                    models.IntegerField(
                        default=6, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    'null_size',
                    models.IntegerField(
                        default=1,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('null_transparent', models.BooleanField(default=True)),
                (
                    'size_config',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='size_range',
                        to='core.sizeconfig',
                    ),
                ),
            ],
        ),
    ]
