/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessControl: typeof import('./src/components/projects/AccessControl.vue')['default']
    AnalyticsPanel: typeof import('./src/components/sidebars/AnalyticsPanel.vue')['default']
    ChartsPanel: typeof import('./src/components/sidebars/ChartsPanel.vue')['default']
    ColormapEditor: typeof import('./src/components/sidebars/ColormapEditor.vue')['default']
    ColormapPreview: typeof import('./src/components/sidebars/ColormapPreview.vue')['default']
    CompareLayerStyle: typeof import('./src/components/sidebars/CompareLayerStyle.vue')['default']
    ControlsBar: typeof import('./src/components/ControlsBar.vue')['default']
    DatasetList: typeof import('./src/components/DatasetList.vue')['default']
    DatasetSelect: typeof import('./src/components/projects/DatasetSelect.vue')['default']
    DatasetsPanel: typeof import('./src/components/sidebars/DatasetsPanel.vue')['default']
    DatasetUpload: typeof import('./src/components/projects/DatasetUpload.vue')['default']
    DetailView: typeof import('./src/components/DetailView.vue')['default']
    FloatingPanel: typeof import('./src/components/sidebars/FloatingPanel.vue')['default']
    LayersPanel: typeof import('./src/components/sidebars/LayersPanel.vue')['default']
    LayerStyle: typeof import('./src/components/sidebars/LayerStyle.vue')['default']
    Map: typeof import('./src/components/map/Map.vue')['default']
    MapTooltip: typeof import('./src/components/map/MapTooltip.vue')['default']
    MapWrapper: typeof import('./src/components/map/MapWrapper.vue')['default']
    NetworksPanel: typeof import('./src/components/sidebars/NetworksPanel.vue')['default']
    NodeAnimation: typeof import('./src/components/sidebars/NodeAnimation.vue')['default']
    ProjectConfig: typeof import('./src/components/projects/ProjectConfig.vue')['default']
    RecursiveTable: typeof import('./src/components/RecursiveTable.vue')['default']
    SideBars: typeof import('./src/components/sidebars/SideBars.vue')['default']
    SliderNumericInput: typeof import('./src/components/SliderNumericInput.vue')['default']
    ToggleCompareMap: typeof import('./src/components/map/ToggleCompareMap.vue')['default']
  }
}
